# Generated by Django 3.2.3 on 2021-07-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210727_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='poster',
        ),
        migrations.AddField(
            model_name='user',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='my_posts', to='network.Post'),
        ),
    ]
