# Generated by Django 3.2.3 on 2021-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210731_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upload',
            field=models.FileField(default='https://i.pinimg.com/originals/a6/58/32/a65832155622ac173337874f02b218fb.png', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
