# Generated by Django 3.2.3 on 2021-08-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_user_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.FileField(upload_to='media/'),
        ),
    ]
